language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: LD2EKQt2bfHt/bpdyyvBcGPwu6UMDZz7ZC/7uoCgSrNXbMJhJlHSfgjONRT3V4AudXXRkwcfZmKaEbYbE6898xOMHEvZN/UY6dN/tDEcUaaE82be2DXFk7bcXOoXGkVv0oNswcwHwBmET/CrQvNN9LAqLOcuNggxpDHDv2K5qiqea39p88QjHMiqpUBfq6FLXdBCmJbqgv2zyGtznxpPSmkeE5RyNt4hbQLsJKptRmkX7I/PJ9UAaKjNw0oOTuQphy7Q9H8OiCkgAMc/CON/eZivk/CTxWuTnQKlCP50pm4T/fokeqtqpVT0fWiuRcbXZJZLqhX2xrfS3e2msoG+bTgEtCQshm8oOFrE7LMltfOhARtVijpmRWlzEZtweDKSRwMSp9WssJxQpbIxV5y2aywzHyNXxxcn/lme4S/gj9mseRCmszko2yMdRdIrNoLC9T0AUEt7nr5Q0HvD+S46lH7mn8uK0U5enWcBi99UyHny/2wUNcTa2k4F1aDNrXXQG9KsLoYI9ttrvT1DJ8v2224MW8f+f44yGIGBf6/taVQabyWUCio5KO1VqwkXirtCu9spzBMMC0BO3dlMt3sRbtZkerx3gFgPGRoLcXmxTxrJ1ZUODTm/eDaGyBmaSLDDLYjztk6/O9zNIiCNHga50wRUO72Wu4BNFKfqNkePpoY=
  app: address-book-aaronhourie
  on:
    repo: aaronhourie/addressbook
    branch: todo_tasks
